/*
 * Sing Up / Sing In
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	// "fmt"
	// "html/template"
	// "io/fs"
	"html/template"
	"log/slog"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	// http.ServeFile(w, r, "./ui/html/singup.html")
	tmpl, err := template.ParseFiles("./ui/html/singup.html")
	if err!= nil{
		slog.Error("Parse template file","error", err)
		return
	}
	tmpl.Execute(w,nil)
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"AuthActivateGet",
		strings.ToUpper("Get"),
		"/auth/activate",
		AuthActivateGet,
	},

	Route{
		"AuthRegisterPost",
		strings.ToUpper("Post"),
		"/auth/register",
		AuthRegisterPost,
	},
}
